// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6WhsUfJBtetLYiFQ7oq2JD
// Component: iAsXuAT5kwWE
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: 6WhsUfJBtetLYiFQ7oq2JD/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: iAsXuAT5kwWE/css
import Rectangle756Icon from "./icons/PlasmicIcon__Rectangle756"; // plasmic-import: TVBO8o15ir/icon
import Polygon1Icon from "./icons/PlasmicIcon__Polygon1"; // plasmic-import: M8jNwnU2Ht/icon
import Polygon3Icon from "./icons/PlasmicIcon__Polygon3"; // plasmic-import: yqp6eBOHPA/icon
import rectangle760PJvucDopGe from "./images/rectangle760.svg"; // plasmic-import: PJvucDOPGe/picture

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"page"}
            data-plasmic-override={overrides.page}
            className={classNames(projectcss.all, sty.page)}
          >
            <div
              data-plasmic-name={"rectangle736"}
              data-plasmic-override={overrides.rectangle736}
              className={classNames(projectcss.all, sty.rectangle736)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__jrsHm
              )}
            >
              {"TSHIRTS"}
            </div>

            <div
              data-plasmic-name={"rectangle753"}
              data-plasmic-override={overrides.rectangle753}
              className={classNames(projectcss.all, sty.rectangle753)}
            />

            <div
              data-plasmic-name={"connectWallet"}
              data-plasmic-override={overrides.connectWallet}
              className={classNames(projectcss.all, sty.connectWallet)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___5EZVt
                )}
              >
                {"CONNECT WALLET"}
              </div>
            </div>

            <Rectangle756Icon
              className={classNames(projectcss.all, sty.svg__cjsPw)}
              role={"img"}
            />

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__mqK26)}
              displayHeight={"43px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"226px"}
              loading={"lazy"}
              src={{
                src: rectangle760PJvucDopGe,
                fullWidth: 226,
                fullHeight: 43,
                aspectRatio: 5.255814
              }}
            />

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__ltBxq)}
              displayHeight={"43px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"226px"}
              loading={"lazy"}
              src={{
                src: rectangle760PJvucDopGe,
                fullWidth: 226,
                fullHeight: 43,
                aspectRatio: 5.255814
              }}
            />

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__oz7Wr)}
              displayHeight={"43px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"226px"}
              loading={"lazy"}
              src={{
                src: rectangle760PJvucDopGe,
                fullWidth: 226,
                fullHeight: 43,
                aspectRatio: 5.255814
              }}
            />

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img___1IwK8)}
              displayHeight={"43px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"226px"}
              loading={"lazy"}
              src={{
                src: rectangle760PJvucDopGe,
                fullWidth: 226,
                fullHeight: 43,
                aspectRatio: 5.255814
              }}
            />

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__kVdq)}
              displayHeight={"43px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"226px"}
              loading={"lazy"}
              src={{
                src: rectangle760PJvucDopGe,
                fullWidth: 226,
                fullHeight: 43,
                aspectRatio: 5.255814
              }}
            />

            <Rectangle756Icon
              className={classNames(projectcss.all, sty.svg__o1ZPn)}
              role={"img"}
            />

            <Rectangle756Icon
              className={classNames(projectcss.all, sty.svg__phEdr)}
              role={"img"}
            />

            <div
              data-plasmic-name={"marketplace"}
              data-plasmic-override={overrides.marketplace}
              className={classNames(projectcss.all, sty.marketplace)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__afXez
                )}
              >
                {"MARKETPLACE"}
              </div>
            </div>

            <div
              data-plasmic-name={"features"}
              data-plasmic-override={overrides.features}
              className={classNames(projectcss.all, sty.features)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__n4VQf
                )}
              >
                {"FEATURES"}
              </div>
            </div>

            <div
              data-plasmic-name={"dashboard"}
              data-plasmic-override={overrides.dashboard}
              className={classNames(projectcss.all, sty.dashboard)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__agWj3
                )}
              >
                {"DASHBOARD"}
              </div>
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___8U89X
              )}
            >
              {"SIZE"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__hnxf7
              )}
            >
              {"COLOR"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__qTOjl
              )}
            >
              {"PROTOCOL"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___3Y4Yp
              )}
            >
              {"PRICE"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__pD5Vm
              )}
            >
              {"SORT BY"}
            </div>

            <Polygon1Icon
              className={classNames(projectcss.all, sty.svg__evh0F)}
              role={"img"}
            />

            <Polygon1Icon
              className={classNames(projectcss.all, sty.svg__ddgjB)}
              role={"img"}
            />

            <Polygon3Icon
              className={classNames(projectcss.all, sty.svg__hcQzx)}
              role={"img"}
            />

            <Polygon1Icon
              className={classNames(projectcss.all, sty.svg__isBGd)}
              role={"img"}
            />

            <Polygon1Icon
              className={classNames(projectcss.all, sty.svg__vD1)}
              role={"img"}
            />

            <div
              data-plasmic-name={"rectangle766"}
              data-plasmic-override={overrides.rectangle766}
              className={classNames(projectcss.all, sty.rectangle766)}
            />

            <div
              data-plasmic-name={"rectangle767"}
              data-plasmic-override={overrides.rectangle767}
              className={classNames(projectcss.all, sty.rectangle767)}
            />

            <div
              data-plasmic-name={"rectangle769"}
              data-plasmic-override={overrides.rectangle769}
              className={classNames(projectcss.all, sty.rectangle769)}
            />

            <div
              data-plasmic-name={"rectangle771"}
              data-plasmic-override={overrides.rectangle771}
              className={classNames(projectcss.all, sty.rectangle771)}
            />

            <div
              data-plasmic-name={"rectangle772"}
              data-plasmic-override={overrides.rectangle772}
              className={classNames(projectcss.all, sty.rectangle772)}
            />

            <div
              data-plasmic-name={"rectangle770"}
              data-plasmic-override={overrides.rectangle770}
              className={classNames(projectcss.all, sty.rectangle770)}
            />

            <div
              data-plasmic-name={"rectangle768"}
              data-plasmic-override={overrides.rectangle768}
              className={classNames(projectcss.all, sty.rectangle768)}
            />

            <div
              data-plasmic-name={"_10SmallAave"}
              data-plasmic-override={overrides._10SmallAave}
              className={classNames(projectcss.all, sty._10SmallAave)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__guEib
                )}
              >
                {"10€\nSmall\nAAVE"}
              </div>
            </div>

            <div
              data-plasmic-name={"_7XSmallTheGraph"}
              data-plasmic-override={overrides._7XSmallTheGraph}
              className={classNames(projectcss.all, sty._7XSmallTheGraph)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__kwprD
                )}
              >
                {"7€\nXSmall\nThe Graph"}
              </div>
            </div>

            <div
              data-plasmic-name={"_10SmallPolygon"}
              data-plasmic-override={overrides._10SmallPolygon}
              className={classNames(projectcss.all, sty._10SmallPolygon)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jY0MI
                )}
              >
                {"10€\nSmall\nPolygon"}
              </div>
            </div>

            <div
              data-plasmic-name={"_10SmallAave2"}
              data-plasmic-override={overrides._10SmallAave2}
              className={classNames(projectcss.all, sty._10SmallAave2)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wtSD
                )}
              >
                {"10€\nSmall\nAAVE"}
              </div>
            </div>

            <div
              data-plasmic-name={"_10MediumEthereum"}
              data-plasmic-override={overrides._10MediumEthereum}
              className={classNames(projectcss.all, sty._10MediumEthereum)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__iJaRy
                )}
              >
                {"10€\nMedium\nEthereum"}
              </div>
            </div>

            <div
              data-plasmic-name={"_5XLarge1Inch"}
              data-plasmic-override={overrides._5XLarge1Inch}
              className={classNames(projectcss.all, sty._5XLarge1Inch)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__p40Kh
                )}
              >
                {"5€\nXLarge\n1inch"}
              </div>
            </div>

            <div
              data-plasmic-name={"_5LargeBinance"}
              data-plasmic-override={overrides._5LargeBinance}
              className={classNames(projectcss.all, sty._5LargeBinance)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zZkwU
                )}
              >
                {"5€\nLarge\nBinance"}
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "page",
    "rectangle736",
    "rectangle753",
    "connectWallet",
    "marketplace",
    "features",
    "dashboard",
    "rectangle766",
    "rectangle767",
    "rectangle769",
    "rectangle771",
    "rectangle772",
    "rectangle770",
    "rectangle768",
    "_10SmallAave",
    "_7XSmallTheGraph",
    "_10SmallPolygon",
    "_10SmallAave2",
    "_10MediumEthereum",
    "_5XLarge1Inch",
    "_5LargeBinance"
  ],

  page: [
    "page",
    "rectangle736",
    "rectangle753",
    "connectWallet",
    "marketplace",
    "features",
    "dashboard",
    "rectangle766",
    "rectangle767",
    "rectangle769",
    "rectangle771",
    "rectangle772",
    "rectangle770",
    "rectangle768",
    "_10SmallAave",
    "_7XSmallTheGraph",
    "_10SmallPolygon",
    "_10SmallAave2",
    "_10MediumEthereum",
    "_5XLarge1Inch",
    "_5LargeBinance"
  ],

  rectangle736: ["rectangle736"],
  rectangle753: ["rectangle753"],
  connectWallet: ["connectWallet"],
  marketplace: ["marketplace"],
  features: ["features"],
  dashboard: ["dashboard"],
  rectangle766: ["rectangle766"],
  rectangle767: ["rectangle767"],
  rectangle769: ["rectangle769"],
  rectangle771: ["rectangle771"],
  rectangle772: ["rectangle772"],
  rectangle770: ["rectangle770"],
  rectangle768: ["rectangle768"],
  _10SmallAave: ["_10SmallAave"],
  _7XSmallTheGraph: ["_7XSmallTheGraph"],
  _10SmallPolygon: ["_10SmallPolygon"],
  _10SmallAave2: ["_10SmallAave2"],
  _10MediumEthereum: ["_10MediumEthereum"],
  _5XLarge1Inch: ["_5XLarge1Inch"],
  _5LargeBinance: ["_5LargeBinance"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    page: makeNodeComponent("page"),
    rectangle736: makeNodeComponent("rectangle736"),
    rectangle753: makeNodeComponent("rectangle753"),
    connectWallet: makeNodeComponent("connectWallet"),
    marketplace: makeNodeComponent("marketplace"),
    features: makeNodeComponent("features"),
    dashboard: makeNodeComponent("dashboard"),
    rectangle766: makeNodeComponent("rectangle766"),
    rectangle767: makeNodeComponent("rectangle767"),
    rectangle769: makeNodeComponent("rectangle769"),
    rectangle771: makeNodeComponent("rectangle771"),
    rectangle772: makeNodeComponent("rectangle772"),
    rectangle770: makeNodeComponent("rectangle770"),
    rectangle768: makeNodeComponent("rectangle768"),
    _10SmallAave: makeNodeComponent("_10SmallAave"),
    _7XSmallTheGraph: makeNodeComponent("_7XSmallTheGraph"),
    _10SmallPolygon: makeNodeComponent("_10SmallPolygon"),
    _10SmallAave2: makeNodeComponent("_10SmallAave2"),
    _10MediumEthereum: makeNodeComponent("_10MediumEthereum"),
    _5XLarge1Inch: makeNodeComponent("_5XLarge1Inch"),
    _5LargeBinance: makeNodeComponent("_5LargeBinance"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
